# Generated by Django 2.1.7 on 2019-09-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='min_read',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
