# Generated by Django 2.1.7 on 2019-09-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tutorial_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('lat', models.CharField(max_length=60)),
                ('longt', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=60)),
            ],
        ),
    ]
