# Generated by Django 2.1.7 on 2019-09-28 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
