# Generated by Django 2.1.7 on 2019-09-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_visitorinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
